Update options page with new styling and radio
microsoft/vscode-dev-chrome-launcher pull request #23
Opened 2022-11-19 01:54 UTC by mirdaki

I've pulled styling information from https://github.com/microsoft/vscode-webview-ui-toolkit. It's a rough approximation, since pulling in the library would require some kind of build system

I've switched to radio buttons for a simple experince and is the recommended approach for just a few items according to the VSCode guidelines from the webview library

This also fixes the flicker issue from #21

2022-11-19 01:55 UTC, mirdaki commented
This is the new options look 
![image](https://user-images.githubusercontent.com/8786151/202828817-2ab96330-7917-420a-84c5-e39c8941e650.png)

2022-12-13 21:42 UTC, joyceerhl requested changes

2022-12-13 21:42 UTC, joyceerhl commented on options.html
> +    <legend>Select a vscode.dev build:</legend>
```suggestion
    <legend>Select a vscode.dev quality:</legend>
```

2023-03-17 20:26 UTC, joyceerhl approved these changes

2023-03-17 22:21 UTC, TylerLeonhardt approved these changes

2023-03-17 22:21 UTC, merged